# Generated by Django 5.2.6 on 2025-11-27 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('sex_other', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.CharField(choices=[('Coaching', 'Coaching'), ('Library', 'Library')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('batch', models.CharField(blank=True, choices=[('Grammar 5-6', 'Grammar Batch 5-6'), ('Grammar 6-7', 'Grammar Batch 6-7'), ('Spoken English', 'Spoken English & PD Batch')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('floor', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('1st Floor', '1st Floor')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('pending', 'Pending'), ('on_hold', 'On Hold')], default='available', max_length=10)),
                ('hold_start_date', models.DateField(blank=True, null=True)),
                ('hold_end_date', models.DateField(blank=True, null=True)),
                ('hold_status', models.CharField(blank=True, choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active')], default='none', max_length=10, null=True)),
                ('hold_request_date', models.DateField(blank=True, null=True)),
                ('hold_request_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
