# Generated by Django 5.2.6 on 2025-12-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_type',
            field=models.CharField(choices=[('new', 'New Admission'), ('existing', 'Already Admitted')], default='new', max_length=10),
        ),
    ]
