# Generated by Django 5.2.6 on 2025-12-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('wifi', 'Wi-Fi / Internet issue'), ('noise', 'Noise / Disturbance'), ('cleaning', 'Cleaning issue'), ('washroom', 'Washroom / Toilet'), ('lost_found', 'Lost & Found'), ('water', 'Water cooler / Drinking water'), ('other', 'Anything else')], max_length=50)),
                ('custom_subject', models.CharField(blank=True, help_text='Used when subject = Anything else', max_length=120)),
                ('message', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.studentprofile')),
            ],
        ),
    ]
