# Generated by Django 5.2.6 on 2025-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_coursecategory_course_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
