# Generated by Django 5.2.6 on 2025-12-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('admission', 'Admission'), ('hold', 'Seat Hold'), ('complaint', 'Complaint'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
