# Generated by Django 5.2.6 on 2025-12-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_notification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_group', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
