# Generated by Django 5.2.6 on 2025-12-26 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_broadcastmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('guest_browsed', 'Guest Browsed'), ('viewed_library', 'Viewed Library Availability'), ('opened_admission', 'Opened Admission Form'), ('selected_coaching', 'Selected Coaching'), ('selected_library', 'Selected Library'), ('selected_library_seat', 'Selected Library Seat')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'intent_type', 'reminder_sent'], name='users_visit_user_id_5e760a_idx')],
            },
        ),
    ]
