# Generated by Django 5.2.6 on 2025-12-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_visitorintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='available_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
