# Generated by Django 5.2.6 on 2025-12-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_seat_available_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorintent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='visitorintent',
            name='users_visit_user_id_5e760a_idx',
        ),
        migrations.AddField(
            model_name='visitorintent',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorintent',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorintent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorintent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visitorintent',
            index=models.Index(fields=['user', 'intent_type'], name='users_visit_user_id_b15ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorintent',
            index=models.Index(fields=['reminder_sent'], name='users_visit_reminde_c40e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorintent',
            index=models.Index(fields=['resolved'], name='users_visit_resolve_d078e2_idx'),
        ),
    ]
