# Generated by Django 5.2.6 on 2025-12-27 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_visitorintent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitorintent',
            name='users_visit_user_id_b15ae8_idx',
        ),
        migrations.AddField(
            model_name='visitorintent',
            name='intent_scope',
            field=models.CharField(choices=[('general', 'General'), ('specific', 'Specific')], default='general', max_length=20),
        ),
        migrations.AddIndex(
            model_name='visitorintent',
            index=models.Index(fields=['user', 'intent_type', 'intent_scope'], name='users_visit_user_id_ec5224_idx'),
        ),
    ]
