# Generated by Django 5.2.6 on 2026-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('Grammar Batch 1', 'Grammar Batch 1'), ('Grammar Batch 2', 'Grammar Batch 2'), ('Grammar Batch 3', 'Grammar Batch 3'), ('Grammar Batch 4', 'Grammar Batch 4'), ('Spoken English 1', 'Spoken English & PD Batch 1'), ('Spoken English 2', 'Spoken English & PD Batch 2')], max_length=50, null=True),
        ),
    ]
