# Generated by Django 5.2.6 on 2026-01-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_studentprofile_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='student',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='hold_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seat_record', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_shift_enabled',
            field=models.BooleanField(default=False, help_text='If True, allows Morning/Evening shifts'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.seat'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shift',
            field=models.CharField(choices=[('full', 'Full Day'), ('morning', 'Morning (8AM - 2PM)'), ('evening', 'Evening (2PM - 8PM)')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hold_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('Grammar Batch 1', 'Grammar Batch 1 (5pm - 6pm)'), ('Grammar Batch 2', 'Grammar Batch 2 (6pm - 7pm)'), ('Grammar Batch 3', 'Grammar Batch 3'), ('Grammar Batch 4', 'Grammar Batch 4'), ('Spoken English 1', 'Spoken English & PD Batch 1'), ('Spoken English 2', 'Spoken English & PD Batch 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='service_type',
            field=models.CharField(choices=[('Coaching', 'Coaching'), ('Library', 'Library')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('on_hold', 'On Hold')], default='pending', max_length=10),
        ),
    ]
