# Generated by Django 5.2.6 on 2026-01-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_seat_student_coursecategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('full', 'Full Day'), ('morning', 'Morning Shift'), ('evening', 'Evening Shift')], default='full', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this assignment is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Seat Assignment',
                'verbose_name_plural': 'Seat Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
