# Generated by Django 5.2.6 on 2026-01-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_seatassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='allow_hold_override',
            field=models.BooleanField(default=False, help_text='Allows teacher-approved assignment even if seat is on hold.'),
        ),
        migrations.CreateModel(
            name='SeatSpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('full', 'Full Day')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='users.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_seat_requests', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'seat', 'status')},
            },
        ),
    ]
