# Generated by Django 5.2.6 on 2026-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_seatassignment_allow_hold_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='hold_end_date',
            field=models.DateField(blank=True, help_text='Shift-level hold end date.', null=True),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='hold_start_date',
            field=models.DateField(blank=True, help_text='Shift-level hold start date.', null=True),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='hold_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active')], default='none', help_text='Hold status specific to this seat assignment (shift-level hold).', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seatspecialrequest',
            unique_together={('seat', 'requested_shift', 'status')},
        ),
    ]
