# Generated by Django 5.2.6 on 2026-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_seatassignment_hold_end_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='unique_active_seatassignment_per_student'),
        ),
    ]
