# Generated by Django 5.2.6 on 2026-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_seatassignment_unique_active_seatassignment_per_student'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('seat', 'shift_type'), name='unique_active_shift_per_seat'),
        ),
    ]
