# Generated by Django 5.2.6 on 2026-01-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_seatassignment_unique_active_shift_per_seat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seatassignment',
            name='unique_active_shift_per_seat',
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='allow_hold_override',
            field=models.BooleanField(default=False, help_text='Teacher-approved temporary or partial assignment during hold'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('Grammar Batch 1', 'Grammar Batch 1'), ('Grammar Batch 2', 'Grammar Batch 2'), ('Grammar Batch 3', 'Grammar Batch 3'), ('Grammar Batch 4', 'Grammar Batch 4'), ('Spoken English 1', 'Spoken English & PD Batch 1'), ('Spoken English 2', 'Spoken English & PD Batch 2')], max_length=50, null=True),
        ),
    ]
