# Generated by Django 5.2.6 on 2026-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_seatholdrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='is_partial',
            field=models.BooleanField(default=False, help_text="If True, this is a 'Tenant' student occupying a seat/shift temporarily."),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='allow_hold_override',
            field=models.BooleanField(default=False, help_text='Teacher-approved override (corresponds with is_partial).'),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='hold_end_date',
            field=models.DateField(blank=True, help_text="End date for this specific assignment's hold.", null=True),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='hold_start_date',
            field=models.DateField(blank=True, help_text="Start date for this specific assignment's hold.", null=True),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='hold_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active')], default='none', help_text="If 'active', this student is away, and their shift is eligible for partial allotment.", max_length=10),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this assignment is currently active (applies to both Owner and Tenant).'),
        ),
    ]
