# Generated by Django 5.2.6 on 2026-01-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_seatassignment_is_partial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatspecialrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seatspecialrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_seat_requests_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seatspecialrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_seat_requests', to='users.studentprofile'),
        ),
    ]
