# Generated by Django 5.2.6 on 2026-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_add_user_to_seatspecialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
    ]
