# Generated by Django 5.2.6 on 2026-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_studentprofile_is_admitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_manual_pending',
            field=models.BooleanField(default=False),
        ),
    ]
