# Generated by Django 5.2.6 on 2026-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('video', 'Video Link'), ('link', 'External Link')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
