# Generated by Django 5.2.6 on 2026-04-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_add_study_material_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='video_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
