# Generated by Django 5.2.6 on 2026-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_studymaterial_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('link', 'Link')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='material_thumbnails/'),
        ),
    ]
