# Generated by Django 5.2.6 on 2026-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_studymaterial_material_type_studymaterial_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
