# Generated by Django 5.2.6 on 2026-04-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_coursequestion_coursereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='users.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_access', to='users.studymaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_access', to='users.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Student Material Accesses',
                'unique_together': {('student', 'material')},
            },
        ),
    ]
