# Generated by Django 5.2.6 on 2026-04-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_coursequestion_answer_courseanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='users.course'),
        ),
    ]
