# Generated by Django 5.2.6 on 2026-04-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_courseanswer_upvotes_coursequestion_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.courseanswer'),
        ),
    ]
