# Generated by Django 5.2.6 on 2026-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_learningreminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningreminder',
            options={'ordering': ['reminder_time', 'reminder_time_daily']},
        ),
        migrations.AddField(
            model_name='learningreminder',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Comma-separated days: 0-6 (Mon-Sun)', max_length=100),
        ),
        migrations.AddField(
            model_name='learningreminder',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='learningreminder',
            name='reminder_time_daily',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningreminder',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
