# Generated by Django 5.2.6 on 2026-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_learningreminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningreminder',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
