# Generated by Django 5.2.6 on 2026-04-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_learningreminder_last_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('about_yourself', models.TextField(help_text='Write something positive about yourself')),
                ('current_post', models.CharField(help_text='Current post and year of selection', max_length=200)),
                ('selection_year', models.IntegerField()),
                ('working_city', models.CharField(help_text='City where you are currently working', max_length=100)),
                ('short_achievement', models.CharField(help_text='Your Big Achievement Name in Shortcut (e.g. Post name short form)', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('photo', models.ImageField(upload_to='achievements/')),
                ('services_used', models.CharField(choices=[('library', 'Library'), ('coaching', 'Coaching'), ('both', 'Both')], max_length=20)),
                ('duration_years', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=0)),
                ('experience_feedback', models.TextField(verbose_name='Experience at ABCD library/coaching')),
                ('other_achievements', models.JSONField(blank=True, default=list, help_text='Other achievements and year of achieving')),
                ('rating', models.IntegerField(default=5)),
                ('abcd_feedback', models.TextField(verbose_name='Feedback for ABCD')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
