# Generated by Django 5.2.6 on 2026-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_studentachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
