# Generated by Django 5.2.6 on 2026-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_studentachievement_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentachievement',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
