# Generated by Django 5.2.6 on 2026-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_studentachievement_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='student', help_text='Role of the complainant when making this complaint', max_length=10),
        ),
    ]
