# Generated by Django 5.2.6 on 2026-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_guidancerequest_chatsession_message_blockedguidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatholdrequest',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
