# Generated by Django 5.2.6 on 2026-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_seatholdrequest_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fee_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
