# Generated by Django 5.2.6 on 2026-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_add_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, help_text='Extra data for UI or logic (e.g., student_id, reminder_type)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('admission', 'Admission'), ('hold', 'Seat Hold'), ('complaint', 'Complaint'), ('payment', 'Payment'), ('fee', 'Fee'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
