# Generated by Django 5.2.6 on 2026-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_notification_meta_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('admission', 'Admission'), ('hold', 'Seat Hold'), ('complaint', 'Complaint'), ('payment', 'Payment'), ('fee', 'Fee'), ('fee_teacher', 'Fee Teacher'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
