# Generated by Django 5.2.6 on 2026-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='broadcast_attachments/'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
