# Generated by Django 5.2.6 on 2026-05-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_broadcastmessage_attachment_broadcastmessage_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='broadcast_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.broadcastmessage')),
            ],
        ),
    ]
