# Generated by Django 5.2.6 on 2026-05-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_broadcastattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='selected_ids',
            field=models.JSONField(blank=True, help_text='List of User IDs if target_group is individuals', null=True),
        ),
    ]
