# Generated by Django 5.2.6 on 2026-05-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_broadcastmessage_selected_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='failed_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
