# Generated by Django 5.2.6 on 2026-05-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_broadcastmessage_failed_user_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('failed', 'Failed'), ('draft', 'Draft')], default='sent', max_length=20),
        ),
    ]
