# Generated by Django 5.2.6 on 2026-05-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_broadcastmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled'), ('failed', 'Failed'), ('processing', 'Processing')], default='sent', max_length=20),
        ),
    ]
