# Generated by Django 5.2.6 on 2026-05-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_broadcastmessage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt identifier for accounting', max_length=30, unique=True)),
                ('payment_date', models.DateField(help_text='The date the teacher recorded this transaction')),
                ('expiry_date', models.DateField(blank=True, help_text="The student's fee expiry date after this submission", null=True)),
                ('service_snapshot', models.TextField(help_text='Frozen description of student service at time of payment')),
                ('months_snapshot', models.JSONField(help_text="Immutable list of months covered. Format: [{'month': '...', 'amount': ..., 'status': '...'}]")),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='users.studentprofile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fee_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Transaction',
                'verbose_name_plural': 'Fee Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='users_feetr_receipt_8058e4_idx'), models.Index(fields=['student', 'created_at'], name='users_feetr_student_feadd6_idx')],
            },
        ),
    ]
