# Generated by Django 5.2.6 on 2026-05-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_feetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interactions', to='users.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_interactions', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Course Interaction',
                'verbose_name_plural': 'Student Course Interactions',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
