# Generated by Django 5.2.6 on 2026-05-08 19:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_studentcourseinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('fee_reminder', 'Fee Collection Reminder')], default='personal', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('auto_delete', models.BooleanField(default=True)),
                ('auto_delete_duration', models.DurationField(default=datetime.timedelta(seconds=21600))),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoFeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_reminders', to='users.todotask')),
            ],
        ),
        migrations.CreateModel(
            name='TodoNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('initial', 'Initial'), ('midway', 'Midway'), ('near_expiry', 'Near Expiry'), ('daily', 'Daily Repeat')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='users.todotask')),
            ],
            options={
                'unique_together': {('task', 'notification_type')},
            },
        ),
    ]
