# Generated by Django 5.2.6 on 2026-05-09 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_todotask_todofeereminder_todonotificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todofeereminder',
            name='student',
        ),
        migrations.RemoveField(
            model_name='todofeereminder',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='todonotificationlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='todonotificationlog',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['-is_pinned', 'expires_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='auto_delete_duration',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='expiry_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todotask',
            name='auto_delete_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todotask',
            name='auto_delete_hours',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='todotask',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='The exact time when this task will expire and potentially auto-delete.', null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='fee_reminder_data',
            field=models.JSONField(blank=True, help_text='Operational memory for teachers tracking quick fee collections.', null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='remind_at',
            field=models.DateTimeField(blank=True, help_text='Next scheduled notification time.', null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='reminder_interval_data',
            field=models.JSONField(blank=True, help_text='Stores metadata about which interval notifications have been sent.', null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('operational', 'Operational'), ('study', 'Study'), ('reminder', 'Reminder'), ('fee_reminder', 'Fee Reminder')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['user', 'status'], name='users_todot_user_id_4c29c5_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['expires_at'], name='users_todot_expires_021b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['remind_at'], name='users_todot_remind__9ef409_idx'),
        ),
        migrations.DeleteModel(
            name='TodoFeeReminder',
        ),
        migrations.DeleteModel(
            name='TodoNotificationLog',
        ),
    ]
