# Generated by Django 5.2.6 on 2026-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_remove_todofeereminder_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='reminder_interval_data',
        ),
        migrations.AddField(
            model_name='todotask',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='notification_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='todotask',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily')], default='once', max_length=10),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='auto_delete_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='auto_delete_hours',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('operational', 'Operational'), ('study', 'Study Goal'), ('fee_reminder', 'Fee Reminder')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='fee_reminder_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
