# Generated by Django 5.2.6 on 2026-05-09 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_todotask_reminder_interval_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='todotask',
            name='users_todot_user_id_4c29c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='todotask',
            name='users_todot_expires_021b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='todotask',
            name='users_todot_remind__9ef409_idx',
        ),
        migrations.RenameField(
            model_name='todotask',
            old_name='archived_at',
            new_name='delete_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='auto_delete_days',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='auto_delete_hours',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='fee_reminder_data',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='last_reminded_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='notification_history',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='remind_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='title',
        ),
        migrations.AddField(
            model_name='todotask',
            name='initial_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='metadata',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='category',
            field=models.CharField(choices=[('FEES', 'To Add Fees'), ('BREAKDOWN', 'Breakdown Tasks'), ('TODO', 'TO-DOs'), ('REMINDER', 'Reminders'), ('NOTE', 'Notebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_hub_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
