# Generated by Django 5.2.6 on 2026-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_todotask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
