# Generated by Django 5.2.6 on 2026-05-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_todotask_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
    ]
