# Generated by Django 5.2.6 on 2026-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_rename_deleted_at_todotask_trashed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['-is_pinned', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
