# Generated by Django 5.2.6 on 2026-05-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_alter_todotask_options_todotask_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='order',
        ),
    ]
