# Generated by Django 5.2.6 on 2026-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_alter_todotask_options_remove_todotask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='next_trigger_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
