# Generated by Django 5.2.6 on 2026-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_todotask_next_trigger_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='next_trigger_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('admission', 'Admission'), ('hold', 'Seat Hold'), ('complaint', 'Complaint'), ('payment', 'Payment'), ('fee', 'Fee'), ('fee_teacher', 'Fee Teacher'), ('reminder', 'Reminder'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
