# Generated by Django 5.2.6 on 2026-05-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_remove_todotask_next_trigger_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedguidance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blockedguidance',
            name='direction',
            field=models.CharField(choices=[('alumni_blocks_student', 'Alumni blocks Student'), ('student_blocks_alumni', 'Student blocks Alumni')], default='alumni_blocks_student', max_length=25),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='guidy_temp/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_starred_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_starred_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='blockedguidance',
            unique_together={('alumni', 'student', 'direction')},
        ),
        migrations.CreateModel(
            name='GroupChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guidy_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='guidy_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Chat Session',
                'verbose_name_plural': 'Group Chat Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='guidy_temp/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted_for_all', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.groupchatsession')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_group_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.groupmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidy_group_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RestrictedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_students', to='users.studentachievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidy_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restricted Student',
                'verbose_name_plural': 'Restricted Students',
                'ordering': ['-created_at'],
                'unique_together': {('alumni', 'student')},
            },
        ),
    ]
