# Generated by Django 5.2.6 on 2026-05-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_blockedguidance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='target_coaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='target_coaching_batches',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='target_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='target_library_floors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='target_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='target_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('course', 'Course'), ('admission', 'Admission'), ('hold', 'Seat Hold'), ('complaint', 'Complaint'), ('payment', 'Payment'), ('fee', 'Fee'), ('fee_teacher', 'Fee Teacher'), ('reminder', 'Reminder'), ('guidy', 'Guidy'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
