# Generated by Django 5.2.6 on 2026-06-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_course_target_alumni_course_target_coaching_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='users.studentprofile'),
        ),
    ]
