# Generated by Django 5.2.6 on 2026-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_coursereview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='password_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
