# Generated by Django 5.2.6 on 2026-07-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_chatsession_user_one_chatsession_user_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatsession',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
    ]
