# Generated by Django 5.2.6 on 2026-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_groupchatsession_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatsession',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
