# Generated by Django 5.2.6 on 2026-07-06 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_groupchatsession_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_group_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
