# Generated by Django 5.2.6 on 2026-07-06 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_groupmessage_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_groupmessages', to=settings.AUTH_USER_MODEL),
        ),
    ]
