# Generated by Django 5.2.6 on 2026-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_message_deleted_by_alter_groupmessage_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
