# Generated by Django 5.2.6 on 2026-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_message_session_directchatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_expired',
            field=models.BooleanField(default=False),
        ),
    ]
