# Generated by Django 5.2.6 on 2026-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_message_media_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='media_expired',
            field=models.BooleanField(default=False),
        ),
    ]
