# Generated by Django 5.2.6 on 2026-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='text', max_length=10),
        ),
    ]
