# Generated by Django 5.2.6 on 2026-07-08 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_alter_groupmessage_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('role_title', models.CharField(blank=True, default='Teacher', max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('detail1', models.CharField(blank=True, max_length=150)),
                ('detail2', models.CharField(blank=True, max_length=150)),
                ('detail3', models.CharField(blank=True, max_length=150)),
                ('about', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
