# Generated by Django 5.2.6 on 2026-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
