# Generated by Django 5.2.6 on 2026-07-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_teacherprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
    ]
