# Generated by Django 5.2.6 on 2026-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_remove_teacherprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='mobile_numbers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='whatsapp_numbers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
