# Generated by Django 5.2.6 on 2026-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_guidyblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=10),
        ),
    ]
