# Generated by Django 5.2.6 on 2026-07-10 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_alter_groupmessage_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_groupmessages', to=settings.AUTH_USER_MODEL),
        ),
    ]
