# Generated by Django 5.2.6 on 2026-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_complaint_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='coaching_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='library_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='service_type',
            field=models.CharField(choices=[('Coaching', 'Coaching'), ('Library', 'Library'), ('Both', 'Both')], max_length=20),
        ),
    ]
