# Generated by Django 5.2.6 on 2026-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_studentprofile_coaching_pending_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
