# Generated by Django 5.2.6 on 2026-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_studentprofile_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
