# Generated by Django 5.2.6 on 2026-07-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_studentachievement_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatSwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('full', 'Full Day')], max_length=10)),
                ('is_temporary', models.BooleanField(default=False)),
                ('temp_hold_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_switch_requests', to='users.studentprofile')),
                ('target_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_requests', to='users.seat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
