# Generated by Django 5.2.6 on 2026-07-28 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_dismissedfeealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='banner_buttons',
            field=models.JSONField(blank=True, default=list, help_text='List of CTA button dicts', null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='broadcast_banners/'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('image', 'Image to Banner'), ('text', 'Write to Banner')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='message_type',
            field=models.CharField(choices=[('broadcast', 'Broadcast Message'), ('banner', 'Ads Banner')], default='broadcast', max_length=20),
        ),
        migrations.CreateModel(
            name='BannerViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='users.broadcastmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
