# Generated by Django 5.2.6 on 2026-07-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_broadcastmessage_banner_buttons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='service_type',
            field=models.CharField(choices=[('Coaching', 'Coaching'), ('Library', 'Library')], max_length=20),
        ),
    ]
