# Generated by Django 5.2.6 on 2026-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_studentprofile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If True, seat is locked by librarian and cannot be occupied'),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_shifts',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of locked shifts: morning, evening, full', max_length=50, null=True),
        ),
    ]
