# Generated by Django 5.2.6 on 2026-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_sync_shift_enabled_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-delete and expiration timestamp', null=True),
        ),
    ]
