# Generated by Django 5.2.6 on 2026-09-03 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_broadcastmessage_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
