# Generated by Django 5.2.6 on 2026-09-10 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_purge_reminder_spam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['user', 'category', 'is_trash', '-created_at'], name='todo_u_cat_tr_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['user', 'is_trash', '-created_at'], name='todo_u_tr_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['is_done', 'is_trash'], name='todo_done_trash_idx'),
        ),
        migrations.AddIndex(
            model_name='todotask',
            index=models.Index(fields=['auto_delete', 'delete_at'], name='todo_del_auto_idx'),
        ),
    ]
