# Generated by Django 5.2.6 on 2026-09-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_seatleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHoldChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=10)),
                ('current_end_date', models.DateField(blank=True, null=True)),
                ('requested_end_date', models.DateField()),
                ('requested_duration', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_change_requests', to='users.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_change_requests', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
