# Generated by Django 5.2.6 on 2026-09-26 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_heal_ghost_hold_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_normalized', models.CharField(db_index=True, max_length=150)),
                ('email_normalized', models.CharField(db_index=True, max_length=254)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quarantine_until', models.DateTimeField(db_index=True)),
                ('user_role', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Quarantine Identity',
                'verbose_name_plural': 'Quarantine Identities',
                'indexes': [models.Index(fields=['username_normalized', 'quarantine_until'], name='users_quara_usernam_2505bb_idx'), models.Index(fields=['email_normalized', 'quarantine_until'], name='users_quara_email_n_743689_idx')],
            },
        ),
    ]
