# Generated by Django 5.2.6 on 2026-10-02 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_quarantineidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='is_hidden_by_student',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if student hid this record from their dashboard/fees view'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['student', 'is_hidden_by_student'], name='users_feetr_student_c0dfee_idx'),
        ),
    ]
