# Generated by Django 5.2.6 on 2026-10-03 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_snapshots(apps, schema_editor):
    FeeTransaction = apps.get_model('users', 'FeeTransaction')
    for tx in FeeTransaction.objects.all():
        updated = False
        if tx.student:
            if not tx.student_name_snapshot:
                tx.student_name_snapshot = tx.student.full_name or ''
                updated = True
            if not tx.roll_number_snapshot:
                tx.roll_number_snapshot = str(tx.student.id)
                updated = True
            if not tx.mobile_snapshot:
                tx.mobile_snapshot = tx.student.mobile_number or ''
                updated = True
            if not tx.course_snapshot:
                tx.course_snapshot = getattr(tx.student, 'batch', '') or getattr(tx.student, 'service_type', '') or ''
                updated = True
        if updated:
            tx.save(update_fields=[
                'student_name_snapshot',
                'roll_number_snapshot',
                'mobile_snapshot',
                'course_snapshot'
            ])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_feetransaction_is_hidden_by_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(db_index=True)),
                ('receipt_number', models.CharField(max_length=50)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(blank=True, default='', max_length=150)),
                ('roll_number', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('months', models.TextField(blank=True, default='')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Fee Transaction Audit',
                'verbose_name_plural': 'Fee Transaction Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherHiddenFeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Hidden Fee Transaction',
                'verbose_name_plural': 'Teacher Hidden Fee Transactions',
            },
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='course_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fee_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='mobile_snapshot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='roll_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='student_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['deleted_at'], name='users_feetr_deleted_ba577c_idx'),
        ),
        migrations.AddField(
            model_name='feetransactionaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherhiddenfeetransaction',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transaction_hides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherhiddenfeetransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_hides', to='users.feetransaction'),
        ),
        migrations.AddIndex(
            model_name='teacherhiddenfeetransaction',
            index=models.Index(fields=['teacher', 'transaction'], name='users_teach_teacher_1e3af6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherhiddenfeetransaction',
            unique_together={('teacher', 'transaction')},
        ),
        migrations.RunPython(backfill_snapshots, reverse_backfill),
    ]
