# Generated by Django 5.2.6 on 2026-10-03 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_links(apps, schema_editor):
    Payment = apps.get_model('users', 'Payment')
    FeeTransaction = apps.get_model('users', 'FeeTransaction')

    for p in Payment.objects.filter(student__isnull=False, fee_transaction__isnull=True):
        candidates = FeeTransaction.objects.filter(student_id=p.student_id, deleted_at__isnull=True)
        matched = []
        month_lower = str(p.month).strip().lower()
        year_str = str(p.year).strip()
        year_short = year_str[-2:]

        for tx in candidates:
            if not isinstance(tx.months_snapshot, list):
                continue
            for item in tx.months_snapshot:
                if not isinstance(item, dict):
                    continue
                raw_m = str(item.get('month') or '').strip().lower()
                if month_lower in raw_m:
                    if year_str in raw_m or f"({year_short})" in raw_m or f"/{year_short}" in raw_m or raw_m == month_lower:
                        matched.append(tx)
                        break

        if len(matched) == 1:
            p.fee_transaction = matched[0]
            p.save(update_fields=['fee_transaction'])


def clear_links(apps, schema_editor):
    Payment = apps.get_model('users', 'Payment')
    Payment.objects.filter(fee_transaction__isnull=False).update(fee_transaction=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_feetransaction_protection_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_fee_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_transaction',
            field=models.ForeignKey(blank=True, help_text='Linked fee receipt/transaction for accounting and editing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.feetransaction'),
        ),
        migrations.CreateModel(
            name='FeeTransactionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_months', models.JSONField(blank=True, default=list)),
                ('new_months', models.JSONField(blank=True, default=list)),
                ('old_payment_date', models.DateField(blank=True, null=True)),
                ('new_payment_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_revisions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='users.feetransaction')),
            ],
            options={
                'verbose_name': 'Fee Transaction Revision',
                'verbose_name_plural': 'Fee Transaction Revisions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RunPython(backfill_links, reverse_code=clear_links),
    ]
