# Generated by Django 5.2.6 on 2026-10-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_feetransaction_revisions_and_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='client_type',
            field=models.CharField(blank=True, choices=[('twa', 'TWA'), ('browser', 'Browser')], default='browser', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
