# Generated by Django 5.2.6 on 2026-10-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_pushsubscription_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='client_type',
            field=models.CharField(blank=True, choices=[('twa', 'TWA'), ('browser', 'Browser'), ('desktop', 'Desktop')], default='browser', max_length=20, null=True),
        ),
    ]
