# Generated by Django 5.2.6 on 2026-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_alter_pushsubscription_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='coaching_fee_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='library_fee_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
