# Generated by Django 5.2.6 on 2026-10-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_studentprofile_coaching_fee_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='service',
            field=models.CharField(
                blank=True,
                choices=[('coaching', 'Coaching'), ('library', 'Library')],
                db_index=True,
                help_text='Service for which fee was paid (coaching vs library, NULL for legacy rows)',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(
                blank=True,
                choices=[('coaching', 'Coaching'), ('library', 'Library')],
                db_index=True,
                help_text='Service for which fee is paid (coaching vs library, NULL for legacy rows)',
                max_length=20,
                null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'service', 'month', 'year')},
        ),
    ]
