# Generated by Django 5.2.6 on 2026-10-04 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_alter_payment_unique_together_feetransaction_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dismissedfeealert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dismissedfeealert',
            name='service',
            field=models.CharField(blank=True, choices=[('coaching', 'Coaching'), ('library', 'Library')], help_text='Service for which alert was dismissed (coaching vs library, NULL for single/legacy)', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dismissedfeealert',
            unique_together={('teacher', 'student', 'expiry_date', 'service')},
        ),
    ]
