# Generated by Django 5.2.6 on 2026-10-06 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def seed_auto_reply_configs(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    AutoReplyConfig = apps.get_model('users', 'AutoReplyConfig')

    asst_user = User.objects.filter(email__iexact='vd19055@gmail.com').first()
    if asst_user:
        AutoReplyConfig.objects.get_or_create(
            user=asst_user,
            defaults={'wait_minutes': 5, 'cooldown_hours': 6, 'is_enabled': False}
        )

    sandeep_user = User.objects.filter(email__iexact='abcd2013baq@gmail.com').first()
    if sandeep_user:
        AutoReplyConfig.objects.get_or_create(
            user=sandeep_user,
            defaults={'wait_minutes': 15, 'cooldown_hours': 6, 'is_enabled': False}
        )


def unseed_auto_reply_configs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_alter_course_qa_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auto_reply_topic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='is_auto_reply',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AutoReplyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('wait_minutes', models.PositiveIntegerField(default=5, help_text='Minutes to wait before auto-replying if owner has not responded')),
                ('cooldown_hours', models.PositiveIntegerField(default=6, help_text='Hours to wait before sending another auto-reply to the same conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto-Reply Configuration',
                'verbose_name_plural': 'Auto-Reply Configurations',
            },
        ),
        migrations.CreateModel(
            name='AutoReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_topic', models.CharField(blank=True, max_length=50)),
                ('matched_keywords', models.CharField(blank=True, max_length=255)),
                ('chosen_response', models.TextField(blank=True)),
                ('variant_index', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('human_replied', 'Cancelled - Human Replied First'), ('cancelled', 'Cancelled'), ('skipped_cooldown', 'Skipped - Cooldown Active')], db_index=True, default='pending', max_length=20)),
                ('human_replied_first', models.BooleanField(default=False)),
                ('flagged_emergency', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_logs', to=settings.AUTH_USER_MODEL)),
                ('direct_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_logs', to='users.directchatsession')),
                ('reply_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_auto_replies', to='users.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_auto_replies', to=settings.AUTH_USER_MODEL)),
                ('trigger_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_auto_replies', to='users.message')),
            ],
            options={
                'verbose_name': 'Auto-Reply Log',
                'verbose_name_plural': 'Auto-Reply Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_auto_reply_configs, unseed_auto_reply_configs),
    ]
