# Generated by Django 5.2.6 on 2026-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_message_auto_reply_topic_message_is_auto_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='hold_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hold_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
