"""
Django settings for abcd_web project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more info, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from decouple import AutoConfig

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)
config = AutoConfig(search_path=BASE_DIR)


# --- VALUES READ FROM .env FILE ---
SECRET_KEY = config('SECRET_KEY', default='django-insecure-development-secret-key-change-in-production')

# The cast=bool makes sure 'True' becomes True (boolean) and 'False' becomes False
DEBUG = config('DEBUG', default=True, cast=bool) 

ALLOWED_HOSTS = [
    h.strip() for h in config(
        'ALLOWED_HOSTS',
        default='127.0.0.1,localhost,testserver,.onrender.com,abcd-web-platform.onrender.com,abcd2013.online,www.abcd2013.online,abcdcampus.in,www.abcdcampus.in,.railway.app'
    ).split(',') if h.strip()
]

# CSRF Trusted Origins for HTTPS Production & Custom Domains
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://*.onrender.com,https://abcd-web-platform.onrender.com,https://abcd2013.online,https://www.abcd2013.online,https://abcdcampus.in,https://www.abcdcampus.in,http://127.0.0.1:8000,http://localhost:8000'
    ).split(',') if o.strip()
]

# Tell Django to trust the X-Forwarded-Proto header from Render's HTTPS reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
if not DEBUG:
    SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# -------------------------------
# SITE / DOMAIN SETTINGS
# -------------------------------

SITE_URL = config(
    "SITE_URL",
    default="http://127.0.0.1:8000"  # local dev fallback
)

# -------------------------------
# INSTALLED APPS
# -------------------------------
INSTALLED_APPS = [
    'daphne',
    'channels',
    'users',  # Your custom app

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # WhiteNoise for static files
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
 
    'social_django',
    'django.contrib.sites',   # REQUIRED for Google auth
]

SITE_ID = 1

ASGI_APPLICATION = 'abcd_web.asgi.application'

REDIS_URL = config('REDIS_URL', default=None)
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# -------------------------------
# MIDDLEWARE
# -------------------------------
MIDDLEWARE = [
    'users.db_utils.GlobalCrashPreventionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise static middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'abcd_web.urls'

WSGI_APPLICATION = 'abcd_web.wsgi.application'

# -------------------------------
# DATABASE
# -------------------------------
DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # SQLite timeout in seconds - wait up to 30 seconds for locks to clear
            # This helps prevent "database is locked" errors during concurrent access
            'OPTIONS': {
                'timeout': 30,
            },
            'CONN_MAX_AGE': None,  # Keep database connection open across requests
        }
    }

# -------------------------------
# PASSWORD VALIDATION
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------
# INTERNATIONALIZATION
# -------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# -------------------------------
# STATIC FILES & WHITENOISE
# -------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # for production collectstatic

# -------------------------------
# MEDIA & CLOUDINARY STORAGE
# -------------------------------
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='').strip()
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='').strip()
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='').strip()

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------
# EMAIL SETTINGS
# -------------------------------

EMAIL_BACKEND = 'users.email_backend.IPv4EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = f'"ABCD Coaching & Library" <{EMAIL_HOST_USER}>'

# -------------------------------
# TEMPLATES
# -------------------------------
TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'users.context_processors.student_context',
            
            'social_django.context_processors.backends',
            'social_django.context_processors.login_redirect',
        ],
    },
}]

# --- NOTIFICATION SERVICE SETTINGS ---
# You can get these credentials when you sign up for a service like Fast2SMS or Twilio
SMS_API_KEY = config('SMS_API_KEY', default='')
SMS_SENDER_ID = 'ABCDCL' # A 6-character ID you register with the SMS provider

# --- META WHATSAPP API SETTINGS ---
# Get these from your Meta for Developers App
WHATSAPP_API_TOKEN = config('WHATSAPP_API_TOKEN', default='')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')

# --- ADMIN/TEACHER CONTACT INFO ---
ADMIN_EMAIL = 'abcd2013baq@gmail.com'
ADMIN_MOBILE_NUMBER = '9827662450' # Include country code, no +
ADMIN_SUPERUSER_NAME = 'Sandeepananda' # For the message template


# -------------------------------
# SIGN IN WITH GOOGLE & AUTH BACKENDS
# -------------------------------
AUTHENTICATION_BACKENDS = (
    'users.auth_backends.EmailOrUsernameModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', default='').strip().strip("'").strip('"')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', default='').strip().strip("'").strip('"')

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = '/post-login/'               # for normal login
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/post-login/'  # for Google social-auth (optional but nice)
LOGIN_ERROR_URL = 'users:login'
SOCIAL_AUTH_LOGIN_ERROR_URL = 'users:login'

# PIPELINE: try existing user by email first, then create if needed
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'users.views.link_existing_account_by_email',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'users.views.set_new_user_flag',
)

# -------------------------------
# LOGGING
# -------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

YOUTUBE_API_KEY = config('YOUTUBE_API_KEY', default='').strip().strip("'").strip('"')
YOUTUBE_CHANNEL_ID = config('YOUTUBE_CHANNEL_ID', default='').strip().strip("'").strip('"')

# --------------------------------------------------------------------------------------------------------------
# WEB PUSH NOTIFICATION SETTINGS
VAPID_PUBLIC_KEY = config('VAPID_PUBLIC_KEY', default='')
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default='')

X_FRAME_OPTIONS = 'SAMEORIGIN'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'guidy_presence_cache',
    }
}

# -------------------------------
# PRODUCTION SECURITY HEADERS
# -------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # SECURE_PROXY_SSL_HEADER already set unconditionally above (line 42)



